name: test


#on:
#  check_run:
#    types: [completed]

on:
  workflow_run:
    workflows: [TiDB Cloud Branch]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
