name: test

on:
  repository_dispatch:
    types: [tidbcloud-branch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - env:
          MESSAGE: ${{ github.event.client_payload.host }}
        run: echo $MESSAGE
        
  
