name: test

on:
  repository_dispatch:
    types: [tidbcloud-branch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: fmt
        run: echo $github.event.client_payload.host
        
  
